name: Kernel Build

on: pull_request

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
    - name: Clean Workspace
      run: rm -rf *.deb *.ddeb *.build *.buildinfo *.changes
    - name: Checkout Sources
      uses: actions/checkout@v3
      with:
          submodules: recursive
          path: pve-port-kernel
    - name: Clean Repository
      run: git -C pve-port-kernel submodule foreach git clean -ffdx
    - name: Build Kernel
      run: |
        rm -rf *.deb *.ddeb *.build *.buildinfo *.changes
        cd pve-port-kernel
        rm debian/control
        debian/rules debian/control
        debuild -e CCACHE_DIR=/var/cache/ccache --prepend-path=/usr/lib/ccache --jobs=auto -b -uc -us
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debs
        path: "*.deb"
